### ISSUE TITLE
relax version on (python) rdflib at least  to 4.1.2

### ISSUE THREAD

**Issue by yarikoptic** [trungdong/prov#107]
Hi @satra -- In 1f8955ee04e331793019f053f11e1f2874f74436 rdflib dependency was added with a strict minimal version to be 4.2.1 which is not present in many debian and ubuntus.  I wondered if there was a specific demand or it could be relaxed at least a bit? ;)

**Comment by trungdong** [comment]
Hi @yarikoptic,

Is this still an issue for you? If so, I can look into testing the package against rdflib 4.1.2.

Skimming [rdflib's change log](https://github.com/RDFLib/rdflib/blob/master/CHANGELOG.md), I think the prov package might work fine with rdflib 4.1.2.

**Comment by satra** [comment]
@yarikoptic and @trungdong - there have been several fixes that have gone into the release of 4.2.2 with many more improvements targeted for 5.0.0. if anything i would suggest making 4.2.2 the requirement instead of going backwards.

**Comment by trungdong** [comment]
I'm assuming this is no longer an issue. Closing.
