### ISSUE TITLE
Version 1.5.0 is failing in some RDF tests

### ISSUE THREAD

**Issue by trungdong** [trungdong/prov#109]
@satra,

I'm planning to do some minor fixes and improvements on 1.5.0 but was surprised to find that it is failing some RDF tests. I was planning to look into it, but if you have time, you might get to the bottom of it much quicker than I will hope to :)
Cheers,

Dong.

**Comment by satra** [comment]
@trungdong - will take a look - that's very weird - possibly some link to changes in rdflib.

**Comment by satra** [comment]
@trungdong - i think this has to do with datetime literals, will check where it broke.
