### ISSUE TITLE
Use pydot again instead of pydotplus

### ISSUE THREAD

**Issue by petrrr** [trungdong/prov#111]
According to the [`HISTORY`](https://github.com/trungdong/prov/blob/master/HISTORY.rst#140-2015-08-13) the switch from `pydot` to `pydotplus` was done approx. 2 year ago. I assume this was done for a lack of activity and missing Python 3 support. Some time back the development of `pydot` was stale and it was not clear which of the many forks to use.

Now the situation with `pydot` seems to have recovered and developments seems to take place and converging at https://github.com/erocarrera/pydot. `pydot` now claims to support python 3. See also https://pypi.python.org/pypi/pydot/1.2.3

Wouldn't it make sense to switch back to `pydot` again?

**Comment by trungdong** [comment]
Many thanks @petrrr for checking this. I looked at pydot build and see that it is now tested against Python 3 (https://travis-ci.org/erocarrera/pydot).

You're right that we switched to pydotplus because it supports Python 3. Having said that, I'm not sure whether both libraries are drop-in equivalent or not.

Is there any compelling reason to go for pydot?

**Comment by petrrr** [comment]
@trungdong: I intend to packages `prov` in Macports, a package manager for the OSX. 

The point here is that dealing with multiple fork of the same/equivalent packages gets quite tricky/cumbersome in such environments, because they are conflicting. If it is possible to avoid this upstream that would help a lot. 

To my understanding `pydotplus` was an intermediate fork which has not seen activity since 2014. The principal contributer to `pydotplus` (@carlos-jenkins) now contributes to `pydot`.

**Comment by trungdong** [comment]
@petrrr,

Thank you for the. I did a quick test with the latest pydot version and it seems to work fine.

Will commit the changes soon.

**Comment by ghisvail** [comment]
+1 @petrrr, same rationales regarding the Debian packaging. A new release with the latest changes would be nice.
