### ISSUE TITLE
Image Export requires pydot

### ISSUE THREAD

**Issue by olf42** [trungdong/prov#114]
To be able to export images with the dot module pydot is required but not installed as a dependency during setup, though it is listed as a test-dependency. 

I would suggest to add 

pydot>=1.2.3 

as a dependency to the setup.py, if this solution is accepted, I will file a pull request.

**Comment by trungdong** [comment]
Hi @olf42,

pydot is already an optional requirement of the package. If you want dot support, install prov with the dot option, e.g. `pip install prov[dot]`.
