### ISSUE TITLE
Bundle not included in RDF seralisation

### ISSUE THREAD

**Issue by cmaumet** [trungdong/prov#116]
Hi @trungdong, @satra,

With the RDF exporter, it looks like bundles are exported as if they were entities. Here is a minimal example:

```
import prov.model as prov

document = prov.ProvDocument()

document.set_default_namespace('http://example.org/0/')
document.add_namespace('ex1', 'http://example.org/1/')
document.add_namespace('ex2', 'http://example.org/2/')

document.entity('e001')

bundle = document.bundle('e001')
bundle.set_default_namespace('http://example.org/2/')
bundle.entity('e001')

print(document.get_provn())

print('---')

print(document.serialize(format='rdf', rdf_format='turtle'))
```

And the output is:
```
document
  default <http://example.org/0/>
  prefix ex2 <http://example.org/2/>
  prefix ex1 <http://example.org/1/>
  
  entity(e001)
  bundle e001
    default <http://example.org/2/>
    
    entity(e001)
  endBundle
endDocument
---
@prefix ex1: <http://example.org/1/> .
@prefix ex2: <http://example.org/2/> .
@prefix prov: <http://www.w3.org/ns/prov#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<http://example.org/0/e001> a prov:Entity .

ex2:e001 a prov:Entity .
```

There is [no formal representation of bundles in turtle (we should use trig instead)](https://github.com/lucmoreau/ProvToolbox/issues/107) but I was nevertheless expecting `ex001` entity to be declared as a `prov:Bundle` in the RDF-turtle serialisation, i.e.:
```
@prefix ex1: <http://example.org/1/> .
@prefix ex2: <http://example.org/2/> .
@prefix prov: <http://www.w3.org/ns/prov#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

ex:e001 a prov:Bundle .

ex2:e001 a prov:Entity .
```

What are you thought on this? Thanks in advance for your feedback!

**Comment by trungdong** [comment]
Hi  @cmaumet 

In my opinion, the fact that a URI is used as the identifier of a bundle does not automatically mean that it is asserted as a `prov:Bundle`. I don't think that there is an inference defined for that.

[This example in PROV-DM](https://www.w3.org/TR/prov-dm/#anexample-provenance-of-provenance), for instance, explicitly asserts the `prov:Bundle` type for the entities.

In fact, if you did not assert `ex:e001` as an entity, we would only know it as a normal URI. Suppose I use a URI as an RDF graph's identifier, I wonder if there is a rule to say that the URI is a graph.

Dong.
