### ISSUE TITLE
visualisation of (undefined/external) agents and activities

### ISSUE THREAD

**Issue by pohutukawa** [trungdong/prov#118]
Agents are rendered in a pentagon/house shape, and activities as a rectangle. If now an agent/activity is not defined/declared within a PROV document, but is external (e.g. defined in a previous PROV document), then the dot graph is topographically still rendered correctly (with edges and the undeclared element rendered in grey), however the shape of the element is an oval (that of an entity).

I suppose that by the context (the type of an edge, e.g. through the `wasAttributedTo` or the `wasGeneratedBy` edges), the `prov` library may be able to declare the shape of the vertex for graph rendering with dot consistently.

Or is there something I'm missing, thus making the rendered graph and its behaviour correct in this context with undeclared vertices?

**Comment by trungdong** [comment]
Hi @pohutukawa,

Thank you for the suggestion. I have implemented it in the above commit in the dev branch. For example, the statement `used(a1, e1, -` will generate the following:
![test](https://user-images.githubusercontent.com/325184/33691482-5265a6d4-dae0-11e7-8c23-f524391b11c7.png)

I'm planning to make a minor release shortly, which will include the above feature.

**Comment by pohutukawa** [comment]
BTW, works fine now. Would be good to get this merged into `master` with a service release.

![kauriid-prov-asb](https://user-images.githubusercontent.com/422922/36708299-41cde826-1bd7-11e8-8a97-c3be842f3724.png)
