### ISSUE TITLE
again: visualisation of (undefined/external) agents and activities

### ISSUE THREAD

**Issue by pohutukawa** [trungdong/prov#123]
I have just (after a longer time) updated my `prov` package with the latest version of the `master` branch, and an issue is re-emerging that was covered in #118: Agents that are not explicitly defined, but just referenced (e.g. from documents outside the current prov document), are rendered as a grey oval, rather than a grey pentagon/house shape.

Is that intentional, or is there a way on how this is to be handled for external references to be displayed correctly? I was very happy with the solution as visible in the last comment on ticket #118.

**Comment by trungdong** [comment]
The commit 93df6ea869bd1230651f5faf9c4a22534fcf219d shown in #118 is still in the dev branch and have not been merged into the master branch yet.

I'll include it in the next release.

**Comment by trungdong** [comment]
Fixed and included in 1.5.3
