### ISSUE TITLE
adding 'undefined' relationships (e.g. from `dcterms`)

### ISSUE THREAD

**Issue by pohutukawa** [trungdong/prov#126]
I want to use a relationship between entities used from Dublin Core Terms, how would I do that using Python's `prov`? I know how that could be done using PROV-N, but not programmatically to generate such a document. Specifically, I want to use `dcterms:hasPart` between two entities in the following fashion:

    document
      prefix kauriid <http://kauriid.nz>
      prefix dcterms <http://purl.org/dc/terms/>
      prefix dia <http://www.dia.govt.nz/>
      
      entity(kauriid:attestations/attestation01)
      entity(kauriid:attestations/ipns/QmP7jb1sU1y8sg85opTPxCzdBcFu9CZ1MAMbvRjnnLe7LK)
      wasDerivedFrom(kauriid:attestations/attestation01, dia:passports/LL124798, -, -, -)
      dcterms:hasPart(kauriid:attestations/ipns/QmP7jb1sU1y8sg85opTPxCzdBcFu9CZ1MAMbvRjnnLe7LK, kauriid:attestations/attestation01, -, -, -)
    endDocument

The reason for this is, that at the time of creation of the PROV trail (generation of `kauriid:attestations/attestation01`), its storage name (on IPFS) is/can not be known. IPFS is 'content addressed' (it derives its storage name from a hash of its content). So later, I need to refer to the IPFS handle `kauriid:attestations/ipns/QmP7jb1sU1y8sg85opTPxCzdBcFu9CZ1MAMbvRjnnLe7LK` instead. But I need to indicate that it contains the `kauriid:attestations/attestation01` entity through the `dcterms:hasPart` relationship.

Now, is there somewhere a tap into a `ProvDocument` or the node (e.g. the entity here) to add a relationship with a 'free' type outside the scope of the `prov` namespace?

**Comment by pohutukawa** [comment]
Another note on this. When reading the definition/notes in the Dublin Core Terms documents, it reads as if the `hasPart` relationship can be applied to both activity -> activity as well as entity -> entity relationships.
Looking at the examples given on PROV, it seems like it's *only* been considered for sub-activities.

**Comment by trungdong** [comment]
Sorry, there is currently no way to add arbitrary relations in the prov package. This is simply not a use case I have considered.

In the example you mention, I would use the [collection](https://www.w3.org/TR/prov-dm/#section-collections) concept and the [hadMember](https://www.w3.org/TR/prov-dm/#dfn-hadmember) relationship.

**Comment by pohutukawa** [comment]
Awesome, I like the approach of using membership to a collection for this. That's just the missing bit that I needed. Cheers!
