### ISSUE TITLE
add `hadPlan` annotation to edge on an activity with a plan

### ISSUE THREAD

**Issue by pohutukawa** [trungdong/prov#127]
I feel like a nag on so many issue tickets recently :-/

Anyway, Sect. 3.7 of the PROV-PRIMER document renders the (dot) visualisation through an edge with a `hadPlan` label. It would be helpful if that could also be added somehow rendered using dot as well.

I suppose that would need to go into either/both of `dot.py` and/or `graph.py`. Though I'm completely out of my depth on understanding on the quick on how they're relating to each other in order to propose the required change myself.

**Comment by trungdong** [comment]
No problems. Keep them coming :)
Love to have all issues logged. It will help other people after you find them too.

The PROV --> Dot conversion is done in the method [`prov.dot.prov_to_dot()`](https://prov.readthedocs.io/en/latest/prov.html#prov.dot.prov_to_dot). Currently, it produces something like the below for `hadPlan`.

![hadplan](https://user-images.githubusercontent.com/325184/45483933-52d5b400-b74a-11e8-8a06-9de77713471b.png)

If you want to have the `hadPlan` label shown in the plan edge, you can change the code I copied here from the above method:
```python
                style = dict(style)  # copy the style
                del style['label']  # not showing label in the second segment
                # the second segment
                dot.add_edge(pydot.Edge(bnode, _get_node(nodes[1]), **style))
                if add_nary_elements:
                    style['color'] = 'gray'  # all remaining segment to be gray
                    for node in nodes[2:]:
                        if node is not None:
                            dot.add_edge(
                                pydot.Edge(bnode, _get_node(node), **style)
                            )
```
You can see on Line 2 I removed the label of the edge. Instead, you could provide the appropriate label there for the end parts of the relation, e.g. `hadPlan`.
(The `style` dict is used to create that part in the last statement)

Hint: To determine the labels for the end parts of a relation, you will need the `attr_name` information when the nodes are enumerated, in the following lines:
```python
            nodes = [
                value for attr_name, value in rec.formal_attributes
                if attr_name in PROV_ATTRIBUTE_QNAMES
            ]
```

**Comment by pohutukawa** [comment]
Excellent. I'll have a stab at it!

**Comment by pohutukawa** [comment]
OK, here's what I've got as a `git diff` on my branch that's got the type inference, so it's slightly different to your code snippet above:

    $ git diff
    diff --git a/prov/dot.py b/prov/dot.py
    index 29dee88..99d1630 100644
    --- a/prov/dot.py
    +++ b/prov/dot.py
    @@ -17,6 +17,7 @@ from __future__ import (absolute_import, division, print_function,
     from datetime import datetime
     import six
     
    +from prov import constants
     from prov.graph import INFERRED_ELEMENT_CLASS
     from prov.model import (
         ProvEntity, ProvActivity, ProvAgent, ProvBundle,
    @@ -137,7 +138,7 @@ DOT_PROV_STYLE = {
         PROV_MEMBERSHIP: {
             'label': 'hadMember', 'fontsize': '10.0'
         },
    -    }
    +}
     
     ANNOTATION_STYLE = {
         'shape': 'note', 'color': 'gray',
    @@ -362,6 +363,9 @@ def prov_to_dot(bundle, show_nary=True, use_labels=False,
                     # the second segment
                     dot.add_edge(pydot.Edge(bnode, _get_node(nodes[1], inferred_types[1]), **style))
                     if add_nary_elements:
    +                    if attr_names[-1].uri == constants.PROV['plan'].uri:
    +                        # For the special case we know, there's the label.
    +                        style['label'] = 'hadPlan'
                         style['color'] = 'gray'  # all remaining segment to be gray
                         for node, inferred_type in zip(nodes[2:], inferred_types[2:]):
                             if node is not None:
