### ISSUE TITLE
prov prefix missing from provjson and provn serializers

### ISSUE THREAD

**Issue by cborromeo** [trungdong/prov#133]
I am trying to serialize my ontology in provjson.  I cannot get the 'prov' prefix to appear in the output.  I tried manually adding it using the add_namespace method and adding it as a default namespace when initializing the ProvDocument object.  Neither technique adds the 'prov' prefix to the output.

I have tried three of the serializers.  The provjson and provn appear to both have this problem.  The RDF/XML serializer appears to export the 'prov' prefix by default without any extra code.  Here is a snippet of my code:

```
      prov_doc = ProvDocument()
      prov_doc.add_namespace('ex', 'http://example.org/')
      ...[add entities and activities]

      # this works:
      print(prov_doc.serialize(format='rdf', rdf_format='trig'))

      # these do not include the prov prefix:
      print(prov_doc.serialize(indent=2))
      print(prov_doc.serialize(format='provn'))
```

**Comment by trungdong** [comment]
The PROV-N and PROV-JSON specs both define `prov` as a built-in namespace and, hence, no (re)definition of `prov` is required.
