### ISSUE TITLE
missing label property in ProvBundle class

### ISSUE THREAD

**Issue by mservillat** [trungdong/prov#136]
ProvBundle class is missing the label property, but this property is tested in prov/dot.py at line 233 (after "if use_labels:", so only if this option is turned on).

This can be solved by adding _label and the label property as it is done for _identifier/identifier in the ProvBundle class (prov/model.py)

However, in PROV, a Bundle is an Entity, therefore one could expect the attributes and method of Entity there.

**Comment by trungdong** [comment]
A [`ProvBundle`](https://prov.readthedocs.io/en/latest/prov.html#prov.model.ProvBundle) object is just a house-keeping construct to hold a list of [`ProvRecord`](https://prov.readthedocs.io/en/latest/prov.html#prov.model.ProvRecord) objects. It has a name (an identifier) so we can refer to the collection of records.

The PROV Data Model considers a bundle as an entity but you will need to have a separate entity record to characterise the bundle with additional attributes, such as types or a label. See [this example](https://www.w3.org/TR/prov-dm/#anexample-provenance-aggregation). Therefore, the [`ProvBundle`](https://prov.readthedocs.io/en/latest/prov.html#prov.model.ProvBundle) class does not support any attributes, including a label property.

**Comment by mservillat** [comment]
Sorry to revive this issue, I understand that a ProvBundle does not support attributes in the model, but the issue is in the code that direclty tests the attribute .label in prov/dot.py at line 252 (after "if use_labels:", so this happens only if this option is turned on). :
>            if use_labels:
>                if bundle.label == bundle.identifier:
>                    bundle_label = f'"{bundle.label}"'



The error is then:
`AttributeError: 'ProvBundle' object has no attribute 'label'`

**Comment by trungdong** [comment]
No problem. Nice catch. Thank you.

I will need to remove the code you found as `ProvBundle` has no `.label` property.
