### ISSUE TITLE
More example usages

### ISSUE THREAD

**Issue by vinisalazar** [trungdong/prov#137]
Hi,

Thank you for providing this package.

The [usage section](https://prov.readthedocs.io/en/latest/usage.html) of the documentation links an [example file](https://github.com/trungdong/prov/blob/master/prov/tests/examples.py). However, this was nowhere to be found. Are there more example usages of the package?

Thank you for any assistance you can provide,

V

**Comment by trungdong** [comment]
Hello @vinisalazar, 

Thanks for alerting me this. I'll update the link in the next release.

In the meantime, please find the file here: https://github.com/trungdong/prov/blob/master/src/prov/tests/examples.py.

There is a short tutorial at http://trungdong.github.io/prov-python-short-tutorial.html,
and a longer example in the notebook on this page: https://openprovenance.org/tutorial/odsc2019.html

**Comment by vinisalazar** [comment]
My apologies, I could not find the file at that location. I updated the link in the documentation page (#138). Thank you for the additional resources.
I'm writing a library that makes extensive use of Prov as a dependency. Hope I can contribute more in the future 👍 

Best,

V
