### ISSUE TITLE
prefixes from external context

### ISSUE THREAD

**Issue by remiadon** [trungdong/prov#140]
as mentioned in https://github.com/bids-standard/BEP028_BIDSprov/issues/49#issuecomment-775930855

Would that be possible to reference a context, and start from there

In my case, something like : 
```python
import prov.model as prov
start_dict = {"@context" : "https://raw.githubusercontent.com/cmaumet/BIDS-prov/context-type-indexing/context.json"}
document = ProvDocument(**start_dict)
document.activity("niiri:random_id")  # `niiri` is defined in the context
```

**Comment by trungdong** [comment]
The prov package does not support JSON-LD yet, it does not know how to parse a JSON-LD context object.

If you want to define a set of namespaces when creating a `ProvDocument` object, you can pass a `namespaces` argument to [`ProvDocument()`](https://prov.readthedocs.io/en/latest/prov.html#prov.model.ProvDocument). You will need to create this argument from the JSON-LD context object yourself.

The `namespaces` argument can be an iterable of [`Namespace`](https://prov.readthedocs.io/en/latest/prov.html#prov.identifier.Namespace) objects, or a `dict` of (prefix, uri).
