### ISSUE TITLE
New ProvRecord objects aren't added to bundles

### ISSUE THREAD

**Issue by Joe-Heffer-Shef** [trungdong/prov#146]
If I initialise a PROV record and pass in a doc/bundle, should I expect this new record to be contained in that doc/bundle?

This script shows that the bundle doesn't contain the record, even though it was passed into the entity constructor.
```
import prov.model

bundle = prov.model.provBundle()
entity = prov.model.ProvEntity(bundle, 'myEntity')

assert bundle.get_records(), 'no records found'
```

**Comment by Joe-Heffer-Shef** [comment]
re: https://github.com/trungdong/prov/blob/master/src/prov/model.py#L244
Should `prov.model.ProvRecord.__init__` do something like the below?:
```
self._bundle = bundle
bundle.add_record(self)
```

**Comment by trungdong** [comment]
I have not considered the use case you presented above. I wonder if there is a reason to create a record in a bundle that way. I would instead do: `bundle.entity('myEntity')`.

To avoid the situation where a record object might contain links to another bundle, the [`add_record()`](https://prov.readthedocs.io/en/latest/_modules/prov/model.html#ProvBundle.add_record) function actually creates a new copy of the given `record` and does not reuse the provided object.
