### ISSUE TITLE
Newbie question on how to work with thematic ontologies

### ISSUE THREAD

**Issue by huard** [trungdong/prov#148]
I'm just starting to delve into provenance and I'm wondering how to use existing ontologies with prov. 

In particular, I'm trying to use the semantics defined in this [ontology](https://github.com/metaclip/vocabularies/blob/master/datasource/datasource.owl) within a ProvDocument.

Those must be naive questions, but here I am: 
Let's assume I created a provenance document and referenced my ontology's namespace:
```
doc=ProvDocument()
doc.add_namespace("ds", "http://www.metaclip.org/datasource/datasource.owl#")
```

A `ds:Dataset` is a subclass of a `prov:entity`. Should I create a new entity with `doc.entity(identifier, other_attributes={prov.model.PROV_TYPE: "ds:Dataset"})` or should I create instead a new record with something like `doc.new_record("ds:Dataset", identifier)` ? The latter doesn't work, because `new_record` requires a `QualifiedName` object that is a member of `PROV_REC_CLS`. 

Thanks in advance,

**Comment by trungdong** [comment]
You should do the former.

To get started, please follow the example provided in the tutorial at https://trungdong.github.io/prov-python-short-tutorial.html.

**Comment by huard** [comment]
Ok, good. Now the problem I'm having is that I want to use the `ds:DatasetSubset` term, which is a subclass of `ds:Step`, itself a subclass of `prov:Derivation`. 

In the [example I'm trying to emulate](https://github.com/metaclip/metaclipR/blob/6b9a0c51f348e12b4814ffe2ff01df667def052e/R/metaclipR.DatasetSubset.R#L118), they create a `ds:DatasetSubset` node and connect it with the parent `ds:Dataset` using an edge with the property `ds:hadDatasetSubset`.

In `prov`, `wasDerivedBy` connects two entities. One entity would be the parent Dataset, but `ds:DatasetSubset` is not a subclass of entity, so I don't understand how to reconcile the prov semantics with the semantics of the `ds:DatasetSubset` term.

**Comment by trungdong** [comment]
Sorry, I have no knowledge of the ontology you mentioned and, hence, am not able to determine what the correct modelling would look like.

Since this is where we discuss the PROV Python package, not how to modelling provenance, I am closing this issue.
