### ISSUE TITLE
Adding a rdfs:label or description to Prov:Activity

### ISSUE THREAD

**Issue by davidporter** [trungdong/prov#152]
How do I add a rdfs:description to a prov:activity with python prov?

Something like:

prov.model.ProvDocument.rdfs:description(some_activity, "Literal_description")

**Comment by trungdong** [comment]
[PROV-O](https://www.w3.org/TR/prov-o/#description-starting-point-terms) specifies that `prov:label` attributes to be mapped to `rdfs:label`. Hence, I think it suffices to add a `prov:label` attribute to the activity in Python. You might want to look at the [example here](https://prov.readthedocs.io/en/latest/usage.html#simple-prov-document) to see how to use it.

I'm closing this issue as it is _not_ an issue of the prov package.

**Comment by davidporter** [comment]
Thank you that answers my question.  More generally, if there is an attribute that isn't mapped/available how can I go about extending or adding it?

**Comment by trungdong** [comment]
You don't need to extend/add RDF properties (to your application) to use them.
You can declare the namespace, say, `rdsf:`, pointing it to the right URI, like in [this tutorial](https://nbviewer.org/github/trungdong/notebooks/blob/master/PROV%20Tutorial.ipynb). Then you can use add attributes under that namespace (see the entity declaration at In[7] in the tutorial).
