### ISSUE TITLE
Change type, label, and value constant names for consistency

### ISSUE THREAD

**Issue by bruth** [trungdong/prov#42]
This is an observation, but [these constants](https://github.com/trungdong/prov/blob/6217972a8a624cbb614d5c1fe0b46f02f66274de/prov/constants.py#L192-L196) do not contain the `_ATTR` part of their names like the other attribute constants.

**Comment by trungdong** [comment]
I agree but am still inclined to keep these as they are (without the `_ATTR`) as they are frequently used while modelling provenance (by the library's users). The `_ATTR` constants, on the other hand, are typically used internally by the library only.
