### ISSUE TITLE
PyPI packages lacks test data.

### ISSUE THREAD

**Issue by petrrr** [trungdong/prov#63]
The package on PyPI seems to differs from the packages obtained via GitHub (different checksums). Moreover, it lacks some the test data and causes some tests to fail.

Ideally, both tarballs should be in sync or at least named differently.

**Comment by trungdong** [comment]
Thank you for reporting this. I'll address this in the next release, which will happen soon.

**Comment by trungdong** [comment]
Fixed in 57a8da7
