### ISSUE TITLE
Ability to add comments to prov model

### ISSUE THREAD

**Issue by smacwan** [trungdong/prov#66]
Currently there is no way to add a comment to a provenance model

**Comment by trungdong** [comment]
Could you elaborate please? Could you give me an example use case?
What type of comments and to which object do you want to attach them?

**Comment by smacwan** [comment]
RDF/TTL documents can have comments (preceded by # in RDF).  It would be nice to have a way to add comments to the model itself and then when the model is serialized those comments would be serialized as well.  An example use case would be when adding something like a legal disclaimer to a document.  Something like this might not necessarily be part of the provenance.

**Comment by trungdong** [comment]
Hi @smacwan, I think this could be useful. I'm guessing that you want to have a (string?) property in `ProvDocument` and `ProvBundle` to hold the content of a comment. Although this is not specified in the PROV data model, I don't see why we can't do that as all the supported file formats (i.e. JSON, XML, and PROV-N) can store comments.

However, with my current workload, I don't think I'll be able to get this implemented anytime soon. If you really need this , I'm very happy to give you some pointers.

**Comment by trungdong** [comment]
I was wrong, JSON does not support comments.

This is a nice feature but not in the scope of the package. Since it didn't get much support, I'm closing the issue.
