### ISSUE TITLE
foaf:name not allowed as entity attribute

### ISSUE THREAD

**Issue by aterrel** [trungdong/prov#74]
Howdy! Thanks for this great library. I'm completely new to WC3 PROV and the prov library and this library has made life quite a bit easier.  

I believe the example below should work, but not sure. I'm trying to add the "foaf:name" attribute to an entity, but getting an error that I'm missing a Prov Identifier. "foaf:givenName" works but now "foaf:name".  Am I doing something wrong or is this indeed a bug?

```python
doc = prov.ProvDocument()
e1 = iris_doc.entity("ex:entity1", {
        'foaf:name': "Entity One",
    })
---------------------------------------------------------------------------
ProvElementIdentifierRequired             Traceback (most recent call last)
<ipython-input-36-0ce33a77955a> in <module>()
      1 doc = prov.ProvDocument()
      2 e1 = iris_doc.entity("ex:entity1", {
----> 3         'foaf:name': "Entity One",
      4     })

/Users/aterrel/miniconda/envs/boldmetrics/lib/python2.7/site-packages/prov/model.pyc in entity(self, identifier, other_attributes)
   1182 
   1183     def entity(self, identifier, other_attributes=None):
-> 1184         return self.new_record(PROV_ENTITY, identifier, None, other_attributes)
   1185 
   1186     def activity(self, identifier, startTime=None, endTime=None,

/Users/aterrel/miniconda/envs/boldmetrics/lib/python2.7/site-packages/prov/model.pyc in new_record(self, record_type, identifier, attributes, other_attributes)
   1170             )
   1171         new_record = PROV_REC_CLS[record_type](
-> 1172             self, self.valid_qualified_name(identifier), attr_list
   1173         )
   1174         self._add_record(new_record)

/Users/aterrel/miniconda/envs/boldmetrics/lib/python2.7/site-packages/prov/model.pyc in __init__(self, bundle, identifier, attributes)
    458         if identifier is None:
    459             # All types of PROV elements require a valid identifier
--> 460             raise ProvElementIdentifierRequired()
    461 
    462         super(ProvElement, self).__init__(bundle, identifier, attributes)

ProvElementIdentifierRequired: An identifier is missing. All PROV elements require a valid identifier.
```

**Comment by trungdong** [comment]
Hello @aterrel,

There are a couple of issues with your example:

1. First, you created a new `ProvDocument` in the `doc` variable, but you used `iris_doc` in the second statement.
2. All namespace prefixes, i.e. `ex:` and `foaf:`, must be declared. They were not in your example.

The exception was raised because the library could not create a valid identifier for the element `e1` as it did not know what namespace `ex:` referred to.

I suggest that you look at the tutorial at http://trungdong.github.io/prov-python-short-tutorial.html for examples of namespace declarations (and more).

**Comment by aterrel** [comment]
Okay cool. The `iris_doc` was a copy paste issue of me trying to simplfy the example. Adding the namespace worked. Thanks!

**Comment by Dcampb007** [comment]
Hello, I've been trying to figure out how to add my own namespace prefixes and attributes to a namespace. Can you assist me? perhaps with an example?

**Comment by trungdong** [comment]
@Dcampb007 
Please refer to the tutorial here: http://trungdong.github.io/prov-python-short-tutorial.html
