### ISSUE TITLE
relax version requirement for networkx to be 1.9 or may be even lower?

### ISSUE THREAD

**Issue by yarikoptic** [trungdong/prov#84]
I was looking into providing backports of Debian package Ghislain Antony Vaillant has prepared for Debian.  A culprit forbidding seamless backporting for debian stable/jessie is demand to have networkx >= 1.10 which was introduced in d916dbc1b292811d7fc1410059c4e8ab61293bbc .  Unfortunately commit message doesn't state why boosting version was required, so I have decided to ask, since package built and all tests passed with 1.9 version of networkx as present on debian jessie.
Or there is some feature which is just not tested which does require 1.10 for sure?

Thank you in advance for the clarification!

**Comment by trungdong** [comment]
@yarikoptic: The networkx package is only used in [this module](https://github.com/trungdong/prov/blob/master/prov/graph.py).
I don't see a reason why a version higher than 1.10 is needed, hence the requirement is now relaxed.
Hope this helps.
