### ISSUE TITLE
QualifiedGeneration for RDF serialisation attribute of Activity instead of Entity

### ISSUE THREAD

**Issue by cmaumet** [trungdong/prov#91]
Hi @satra, @trungdong,

I have continued my tests of the RDF serialisation and I think there might be an issue with the  `prov:qualifiedGeneration`. 

On the PROV website the `prov:qualifiedGeneration` is an attribute of a `prov:Entity` but when I run the RDF export I get it as an attribute of a `prov:Activity`: 
```
niiri:9e0461b9-f8f3-4ea2-b9be-a215242106b7 a prov:Activity ;
    rdfs:label "NIDM-Results export"^^xsd:string ;
    prov:qualifiedGeneration [ a prov:Generation ;
    prov:atTime "2016-10-12T13:34:38.449691"^^xsd:dateTime ] .
```

Previously we had:
```
niiri:53356c68-de61-4d95-a5e5-f3c1625f1979 a nidm_NIDMResults:,
        prov:Bundle,
        prov:Entity ;
        rdfs:label "NIDM-Results" ;
        nidm_version: "1.3.0"^^xsd:string ;
        prov:qualifiedGeneration [ a prov:Generation ;
        prov:activity niiri:f5611270-8992-45ea-a68f-5686ab00b29c ;
        prov:atTime "10:45:52.725385"^^xsd:dateTime ] .
```

**Comment by satra** [comment]
@cmaumet - could you paste the prov document that you are trying to serialize here? at this point any output should match (subject to #34) the java toolbox.

**Comment by cmaumet** [comment]
Yes, that's a good point @satra! The provn document is available here: https://provenance.ecs.soton.ac.uk/store/documents/114816/. 

I think the [turtle serialisation](https://provenance.ecs.soton.ac.uk/store/documents/114816.ttl) from the prov store is indeed consistent with the export from the prov python toolbox.

But the [specification of `prov:qualifiedGeneration`](https://www.w3.org/TR/prov-o/#qualifiedGeneration), says that the domain is `prov:Entity` (not `prov:Activity`). Is that an inconsistency?

**Comment by satra** [comment]
in the provn document, i see

```
activity(niiri:e9a492a1-edfb-44f0-8e6f-deffab188fc8, -, -, [prov:label="NIDM-Results export"])
...
wasGeneratedBy(niiri:e9a492a1-edfb-44f0-8e6f-deffab188fc8, -, 2016-10-13T11:30:13.954000+01:00)
```

you would get the appropriate output if the activity IRI was in it's correct position and/or if you had the entity:

```
wasGeneratedBy(-, niiri:e9a492a1-edfb-44f0-8e6f-deffab188fc8, 2016-10-13T11:30:13.954000+01:00)
```

effectively the original document is saying the `activity wasGeneratedBy something`. since prov nor the rdf export is imposing any constraint check, this passed through as valid.

**Comment by cmaumet** [comment]
Thank you for catching this @satra! 

It was indeed a bug in the way the document was created as part of the FSL exporter. Now fixed! So, the RDF export is fine.
