### ISSUE TITLE
xsd:QName should not be in RDF test files

### ISSUE THREAD

**Issue by trungdong** [trungdong/prov#92]
Some of the `.ttl` test files added in 14715177f86c7e0524dee89972bc8de2815f3efd use `xsd:QName`, which is no longer valid as a type for qualified names.
All such literals should be just prefixed names in Turtle.

**Comment by trungdong** [comment]
@satra 

I guess you may have converted the JSON test files to the TTL files above?
I changed `xsd:QName` into `prov:QUALIFIED_NAME` in d71604b8adbe8d5821afffc53bfce00bbf8c3b10.

**Comment by satra** [comment]
@trungdong - yes, i converted them using the prov web service a while back. i'll regenerate them and check tomorrow.

**Comment by satra** [comment]
@trungdong - prov store url isn't working right now (https://provenance.ecs.soton.ac.uk/validator/provapi/documents/), will try again tomorrow.

**Comment by satra** [comment]
@trungdong - this looks to be in the jsonld branch. 

how would sth like:

```
"$": "abcde",
"type": "prov:QUALIFIED_NAME"
```

be distinguished in turtle from a string?

**Comment by trungdong** [comment]
Hi @satra, I'm not sure I'm following. The test files in d71604b are PROV-JSON test files. They are not JSON-LD files.

The example you copied is a qualified name from the default namespace of the document, hence, it has no prefix. The [default namespace](https://www.w3.org/Submission/2013/SUBM-prov-json-20130424/#PROV-JSON-overview) can be declared in PROV-JSON, allowing qualified names like the above to be resolved correctly.

**Comment by satra** [comment]
@trungdong - i was trying to understand how qname's would map

just to make the example more concrete, then this should translate to something like this in turtle. 

```
@prefix : <http://example.org/> .

... :abcde
```

and the distinction between a URI and a QName is whether it's defined in the set of namespace prefix-es in the document.

therefore, in the following turtle document

```
@prefix : <http://example.org/> .
:a :b <http://example.org/abcde> .
```
each element would translate to a `prov:QualifiedName` right?

and would come back out as:
```
@prefix : <http://example.org/> .
:a :b :abcde .
```

**Comment by trungdong** [comment]
You have it all correct. In RDF, there is no `prov:QUALIFIED_NAME`. A qualified name in PROV-DM is represented as an element/URI in RDF.

BTW, you don't even need to maintain the same prefix in the RDF representation, although it's nice to do so.

**Comment by trungdong** [comment]
@satra 
I have removed those xsd:QName by converting the JSON files to RDF using ProvToolbox (which is behind the translator at provenance.ecs.soton.ac.uk).

Three files now fail your test: `derivation11.ttl`, `derivation12.ttl`, `derivation13.ttl`. They use `prov:qualifiedRevision` and `prov:Revision` (instead of `prov:qualifiedDerivation` and `prov:Derivation`). Do you support those in your RDF output?

**Comment by satra** [comment]
@trungdong - just sent a pull request addressing these failures.
