### ISSUE TITLE
Namespaces in RDF serialisation

### ISSUE THREAD

**Issue by cmaumet** [trungdong/prov#95]
Hi @satra, @trungdong,

Could the namespaces defined using the prov toolbox be passed to the json-ld (RDF) export?

When exporting the following provn document: https://provenance.ecs.soton.ac.uk/store/documents/114819/
with current `master` I get a json-ld file where all namespaces are replaced by their URIs (e.g. `http://purl.org/nidash/nidm#` instead of `nidm:`):  https://github.com/cmaumet/nidmresults-fsl/blob/test_jsonld/test/exported/ex_fsl_default_130/nidm.jsonld (for some reason I can't upload this document on the prov store).

Is there something specific to do for the namespaces to be passed?

Currently I am using:
```
jsonld_txt = self.doc.serialize(format='rdf', rdf_format='json-ld')
provn_txt = self.doc.serialize(format='provn')
```

**Comment by satra** [comment]
@cmaumet - that particular doc is private :(

**Comment by cmaumet** [comment]
Sorry! Now public...

**Comment by satra** [comment]
ok this works:

```python
context = {"nidm": "http://purl.org/nidash/nidm#", "prov": "http://www.w3.org/ns/prov#", "dc": "http://purl.org/dc/terms/", "crypto": "http://id.loc.gov/vocabulary/preservation/cryptographicHashFunctions#", "niiri": "http://iri.nidash.org/", "sdo": "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#", "rdfs": "http://www.w3.org/2000/01/rdf-schema#", "nif": "http://uri.neuinfo.org/nif/nifstd/", "xsd": "http://www.w3.org/2001/XMLSchema#", "stato": "http://purl.obolibrary.org/obo/"}

print(d.serialize(format='rdf', rdf_format='json-ld', context=context))
```

i think this is an rdflib-jsonld issue as the namespaces are being created in the graph, as can be seen here:

https://github.com/trungdong/prov/blob/master/prov/serializers/provrdf.py#L205

**Comment by cmaumet** [comment]
Thanks @satra! I am closing this issue as this is now open for discussion at: https://github.com/RDFLib/rdflib-jsonld/issues/43.
